name: Airline Booking Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Verify AWS CLI Installation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws --version
          aws s3 ls

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync Frontend/dist s3://airline-booking-frontend --delete --debug
          
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          # Decode and save EC2 key
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2_key.pem
          chmod 400 ec2_key.pem
          
          # Upload backend code to EC2
          scp -i ec2_key.pem -r Backend/* $EC2_USER@$EC2_HOST:~/Backend

          # SSH into EC2 and deploy
          ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Ensure environment variables are set
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ~/Backend/.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ~/Backend/.env

            # Navigate to the Backend directory
            cd ~/Backend

            # Install dependencies and restart the server
            npm install
            pm2 restart all || pm2 start App.js
          EOF
